spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: reader
    password: 123456
    url: jdbc:mysql://172.20.29.103:3306/nano_eval_local?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

