spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: campephilus
    password: yplBTG6yeu6pw61k
    url: jdbc:mysql://rm-wz90i0nbmc54e83r40o.mysql.rds.aliyuncs.com/campephilus-dev?characterEncoding=utf-8&useSSL=false?serverTimezone=GMT
#  jpa:
#    hibernate:
#      ddl-auto: update

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath*:com/**/mapper/*.xml
